package com.corrsolutions.domain;// default package
// Generated 29-Jul-2013 09:30:26 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * com.corrsolutions.domain.Game generated by hbm2java
 */
@Entity
@Table(name="game"
    ,catalog="quest"
)
public class Game  implements java.io.Serializable {


     private Integer gameId;
     private GameUser gameUser;
     private int score;
     private String elapsedTime;
     private Date createdOn;

    public Game() {
    }

	
    public Game(GameUser gameUser, int score) {
        this.gameUser = gameUser;
        this.score = score;
    }
    public Game(GameUser gameUser, int score, String elapsedTime, Date createdOn) {
       this.gameUser = gameUser;
       this.score = score;
       this.elapsedTime = elapsedTime;
       this.createdOn = createdOn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="game_id", nullable=false)
    public Integer getGameId() {
        return this.gameId;
    }
    
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public GameUser getGameUser() {
        return this.gameUser;
    }
    
    public void setGameUser(GameUser gameUser) {
        this.gameUser = gameUser;
    }
    
    @Column(name="score", nullable=false)
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }
    
    @Column(name="elapsed_time", length=50)
    public String getElapsedTime() {
        return this.elapsedTime;
    }
    
    public void setElapsedTime(String elapsedTime) {
        this.elapsedTime = elapsedTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }




}


